"""Anti-aliased TFT_eSPI font (.vlw) generator -> C arrays in src/assets.

Uses Pillow instead of the Processing sketch that ships with TFT_eSPI; fonts
are compiled into the firmware, no LittleFS upload needed. Source font is
Bahnschrift from Windows (DIN-like, has Latin-1 and Cyrillic).
Used by the modern WEATHER and MARKETS modes and the menu; the classic modes
keep their Volkswagen fonts.

Run from the project root:  python tools/make_vlw.py
"""
import os
import struct
from PIL import Image, ImageDraw, ImageFont

TTF = "C:/Windows/Fonts/bahnschrift.ttf"
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "assets")

ASCII = "".join(chr(c) for c in range(32, 127))
LATIN1 = "".join(chr(c) for c in range(0xC0, 0x100))            # accented Latin for city names
CYRILLIC = "".join(chr(c) for c in range(0x410, 0x450)) + "ІіЇїЄєҐґЁё"
TEXT = ASCII + LATIN1 + CYRILLIC + "°ʼ’"
NUM = "0123456789-+.,:%$° CKMB"   # large numbers: temperature, price, time

# (name, size px, variation, character set)
FONTS = [
    ("BsTiny",  12, b"SemiBold", TEXT),   # metric labels
    ("BsMed",   20, b"SemiBold", TEXT),   # values, city, coin symbols
    ("BsNum",   44, b"SemiLight", NUM),   # temperature, price
    ("BsClock", 68, b"Light", "0123456789: "),   # time
]


def glyph(font, ch):
    """Rasterise one glyph: (w, h, advance, dY above baseline, dX, bytes)."""
    size = font.size * 3
    im = Image.new("L", (size, size), 0)
    ox, oy = font.size, font.size * 2
    ImageDraw.Draw(im).text((ox, oy), ch, font=font, fill=255, anchor="ls")
    adv = int(round(font.getlength(ch)))
    box = im.getbbox()
    if box is None:
        return 0, 0, adv, 0, 0, b""
    x0, y0, x1, y1 = box
    return (x1 - x0, y1 - y0, adv, oy - y0, x0 - ox, im.crop(box).tobytes())


def build(name, px, variant, chars):
    font = ImageFont.truetype(TTF, px)
    font.set_variation_by_name(variant)
    chars = sorted(set(chars), key=ord)
    glyphs = [(ord(c),) + glyph(font, c) for c in chars]
    ascent, descent = font.getmetrics()

    data = bytearray(struct.pack(">6i", len(glyphs), 11, px, 0, ascent, descent))
    for code, w, h, adv, dy, dx, _ in glyphs:
        data += struct.pack(">7i", code, h, w, adv, dy, dx, 0)
    for *_, bmp in glyphs:
        data += bmp

    path = os.path.join(OUT, name + ".h")
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/make_vlw.py — do not edit by hand.\n")
        f.write(f"// Bahnschrift {variant.decode()} {px}px, {len(glyphs)} glyphs.\n")
        f.write("#pragma once\n#include <pgmspace.h>\n\n")
        f.write(f"const uint8_t {name}[] PROGMEM = {{\n")
        for i in range(0, len(data), 24):
            f.write("  " + ",".join(str(b) for b in data[i:i + 24]) + ",\n")
        f.write("};\n")
    print(f"{name}: {len(glyphs)} glyphs, {len(data)} bytes")


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for args in FONTS:
        build(*args)
